---
title: "Baseball Data Select" 
author: "Evan Burns"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(dplyr)

baseball_full <- read.csv("Data/Retrosheet.csv")

team_win <- read.csv("Data/Season Results.csv")

baseball_setup <- subset(baseball_full, Year != 2020 & Year != 2021)

baseball_setup_w_away <- left_join(baseball_setup, team_win, by = c("Year" = "Year","Away_Team" = "Team_Abb")) %>% #Adding away team win percentage
  select(-Team) %>%
  select(-c(110:175)) %>%
  rename(
    Away_Win_Percentage = Win_Percentage,
    Away_Playoffs = Playoffs,
    Away_WS = WS,
    Away_Win_P_Cat = Win_P_Cat
  )

baseball_setup_w_both <- left_join(baseball_setup_w_away, team_win, by = c("Year" = "Year", "Home_Team" = "Team_Abb")) %>% #Adding home team win percentage
  rename(
    Home_Win_Percentage = Win_Percentage,
    Home_Playoffs = Playoffs,
    Home_WS = WS,
    Home_Win_P_Cat = Win_P_Cat
  )

baseball_allmlb_final <- baseball_setup_w_both %>% #Changing California Angels to ANA Angels
  mutate(
    Team_Winner = gsub("CAL", "ANA", Team_Winner),
    Away_Team = gsub("CAL", "ANA", Away_Team),
    Home_Team = gsub("CAL", "ANA", Home_Team)
  )

team_names <- unique(baseball_allmlb_final$Team_Winner)

#Takes each team in team_names, creates a new data frame for each team involving only games that team played, creates a new variable called Home (1 if Home, 0 if Away), and creates another new variable called teamabbreviation_win (eg. TEX_win) (1 if Win, 0 if Loss)
for (team in team_names) {
  df_name <- paste0(team, "_games")
  team_data <- subset(baseball_allmlb_final, Away_Team == team | Home_Team == team)
  team_data <- team_data %>%
    mutate(Home = ifelse(Away_Team == team, 0, 1),
           !!paste0(team, "_win") := ifelse(Team_Winner == team, 1, 0)
           )
  assign(df_name, team_data)
  ###
  # file_path <- paste0("~/Desktop/Senior Year Work/Causal Inference/Baseball Data/Team Datasets", "/", df_name, ".csv")
  # write.csv(team_data, file_path, row.names = FALSE)
}

# write_csv(baseball_allmlb_final, "~/Desktop/Senior Year Work/Causal Inference/Baseball Data/Baseball_allmlb_Clean.csv")
```
